// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// ibm
Rcpp::List ibm(const int nbInd, const int length, const double prob_mut, const int loci, const Eigen::MatrixXf& CovarMatrix, bool pursue, const Eigen::MatrixXf ParentGenetValue, bool intratrait, const Eigen::MatrixXf matrixEpistasisIntra, bool intertraits, const Eigen::MatrixXf matrixEpistasisInter);
RcppExport SEXP IBMepis_ibm(SEXP nbIndSEXP, SEXP lengthSEXP, SEXP prob_mutSEXP, SEXP lociSEXP, SEXP CovarMatrixSEXP, SEXP pursueSEXP, SEXP ParentGenetValueSEXP, SEXP intratraitSEXP, SEXP matrixEpistasisIntraSEXP, SEXP intertraitsSEXP, SEXP matrixEpistasisInterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type nbInd(nbIndSEXP);
    Rcpp::traits::input_parameter< const int >::type length(lengthSEXP);
    Rcpp::traits::input_parameter< const double >::type prob_mut(prob_mutSEXP);
    Rcpp::traits::input_parameter< const int >::type loci(lociSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXf& >::type CovarMatrix(CovarMatrixSEXP);
    Rcpp::traits::input_parameter< bool >::type pursue(pursueSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXf >::type ParentGenetValue(ParentGenetValueSEXP);
    Rcpp::traits::input_parameter< bool >::type intratrait(intratraitSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXf >::type matrixEpistasisIntra(matrixEpistasisIntraSEXP);
    Rcpp::traits::input_parameter< bool >::type intertraits(intertraitsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXf >::type matrixEpistasisInter(matrixEpistasisInterSEXP);
    rcpp_result_gen = Rcpp::wrap(ibm(nbInd, length, prob_mut, loci, CovarMatrix, pursue, ParentGenetValue, intratrait, matrixEpistasisIntra, intertraits, matrixEpistasisInter));
    return rcpp_result_gen;
END_RCPP
}
