# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ibm <- function(nbInd, length, prob_mut, loci, CovarMatrix, pursue, ParentGenetValue, intratrait, matrixEpistasisIntra, intertraits, matrixEpistasisInter) {
    .Call('IBMepis_ibm', PACKAGE = 'IBMepis', nbInd, length, prob_mut, loci, CovarMatrix, pursue, ParentGenetValue, intratrait, matrixEpistasisIntra, intertraits, matrixEpistasisInter)
}

